


-- List the number of films per category.

USE sakila;

SELECT COUNT(f.film_id) AS Number_of_films, c.name
FROM category AS c
JOIN film_category as f
ON c.category_id = f.category_id
GROUP BY c.name;

-- Retrieve the store ID, city, and country for each store.

SELECT s.store_id, c.city, co.country 
FROM address as a
JOIN store as s
ON a.address_id = s.address_id
JOIN city as c
ON a.city_id = c.city_id
JOIN country as co
ON co.country_id = c.country_id;

-- Calculate the total revenue generated by each store in dollars.

SELECT SUM(p.amount), st.store_id
FROM payment p
JOIN staff s 
ON s.staff_id = p.staff_id
JOIN store st
ON st.store_id = s.store_id
GROUP BY st.store_id;

-- Determine the average running time of films for each category.

 SELECT 
    c.name AS category_name,
    AVG(f.length) AS average_runtime,
    CONCAT(ROUND(AVG(f.length), 2), ' min') AS average_runtime_formatted
FROM film f
INNER JOIN film_category fc ON f.film_id = fc.film_id
INNER JOIN category c ON fc.category_id = c.category_id
GROUP BY c.category_id, c.name
ORDER BY average_runtime DESC;

